### ISSUE TITLE
Not issue, upgrade maybe - one service for all models

### ISSUE THREAD

**Issue by goors** [cusspvz/rethinkdb-express-api-boilerplate#5]
Hi,

you got this index.js with bunch of services exported. But, logic is same for every of them. What i mean is this

service1.js - uses post/delete/patch/put
service2.js - uses post/delete/patch/put
service3.js - uses post/delete/patch/put

What i am thinking is to use one service for everything with endpoint taken from url model name.
So instead of having same number of services as number models, you just have one service.

What do you think? Is this doable?

**Comment by cusspvz** [comment]
Well, the services are separated because you usually want to separate those.

Imagine a case where you have: Users, Cars and Gas stations as models.
You just create 3 files, as you do for each model, and if later you need to create a custom endpoint into "Gas Stations" service, you know it is at the certain file.

If you mean that you could include all of them into the `index.js`, or even remove the folder `services` and place a `services.js` file with all in, yeah, you can. But if it gets bigger, you'll get all those settings into one bag.
